
  services:
      db:
        image: postgres:latest
        container_name: db_bronting
        ports:
          - 5436:5432
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=bronting_db

